import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:edusync/domain/models/school_task.dart';

void main() {
  group('SchoolTask serialization & attribution (D-01, D-02)', () {
    test('serializes and deserializes full SchoolTask with source, sourceId, metadata, and Timestamp', () {
      final createdAt = DateTime(2026, 9, 23, 10, 30);
      final dueDate = DateTime(2026, 9, 25, 0, 0);
      final completedAt = DateTime(2026, 9, 23, 18, 15);

      final task = SchoolTask(
        id: 'task_1',
        familyId: 'jankiewicz_family',
        title: 'Powtórzyć dział z biologii',
        description: 'Rozdział 4: Układ krwionośny',
        dueDate: dueDate,
        priority: TaskPriority.high,
        assignedTo: TaskAssignee.student,
        subject: 'Biologia',
        isCompleted: true,
        createdByRole: 'parent',
        createdByName: 'Tata',
        createdAt: createdAt,
        completedByRole: 'student',
        completedByName: 'Oskar',
        completedAt: completedAt,
        source: TaskSource.exam,
        sourceId: 'exam_bio_4',
        metadata: const {'chapter': 4, 'autoGenerated': true},
      );

      expect(
        task.attributionLabel,
        equals('Dodał: Tata • Ukończył: Oskar'),
      );

      final json = task.toJson();
      final roundTrip = SchoolTask.fromJson(json, 'task_1');

      expect(roundTrip.id, equals('task_1'));
      expect(roundTrip.familyId, equals('jankiewicz_family'));
      expect(roundTrip.title, equals('Powtórzyć dział z biologii'));
      expect(roundTrip.description, equals('Rozdział 4: Układ krwionośny'));
      expect(roundTrip.priority, equals(TaskPriority.high));
      expect(roundTrip.assignedTo, equals(TaskAssignee.student));
      expect(roundTrip.subject, equals('Biologia'));
      expect(roundTrip.isCompleted, isTrue);
      expect(roundTrip.createdByRole, equals('parent'));
      expect(roundTrip.createdByName, equals('Tata'));
      expect(roundTrip.completedByRole, equals('student'));
      expect(roundTrip.completedByName, equals('Oskar'));
      expect(roundTrip.source, equals(TaskSource.exam));
      expect(roundTrip.sourceId, equals('exam_bio_4'));
      expect(roundTrip.metadata?['chapter'], equals(4));
      expect(
        roundTrip.attributionLabel,
        equals('Dodał: Tata • Ukończył: Oskar'),
      );

      // Verify Firestore Timestamp support in fromJson
      final firestoreJson = {
        ...json,
        'dueDate': Timestamp.fromDate(dueDate),
        'createdAt': Timestamp.fromDate(createdAt),
      };
      final fromTimestamp = SchoolTask.fromJson(firestoreJson, 'task_ts');
      expect(fromTimestamp.dueDate, equals(dueDate));
      expect(fromTimestamp.createdAt, equals(createdAt));
    });

    test('handles optional fields and uncompleted attribution label cleanly', () {
      final task = SchoolTask(
        id: 'task_partial',
        familyId: 'jankiewicz_family',
        title: 'Kupić zeszyt w kratkę',
        createdByRole: 'student',
        createdByName: 'Oskar',
        createdAt: DateTime(2026, 9, 23),
      );

      expect(task.attributionLabel, equals('Dodał: Oskar'));
      expect(task.hasNoDueDate, isTrue);
      expect(task.description, isNull);
      expect(task.subject, isNull);
    });
  });

  group('SchoolTask chronological classification (D-05)', () {
    test('classifies today at 00:00:00 as isDueToday and never isOverdue', () {
      final now = DateTime.now();
      final todayMidnight = DateTime(now.year, now.month, now.day);
      final yesterday = todayMidnight.subtract(const Duration(days: 1));
      final tomorrow = todayMidnight.add(const Duration(days: 1));

      final dueTodayTask = SchoolTask(
        id: 't_today',
        familyId: 'jankiewicz_family',
        title: 'Dzisiejsze zadanie',
        dueDate: todayMidnight,
        createdByRole: 'parent',
        createdByName: 'Tata',
        createdAt: now,
      );

      final overdueTask = dueTodayTask.copyWith(
        id: 't_overdue',
        dueDate: yesterday,
      );

      final upcomingTask = dueTodayTask.copyWith(
        id: 't_upcoming',
        dueDate: tomorrow,
      );

      final noDateTask = dueTodayTask.copyWith(
        id: 't_nodate',
        clearDueDate: true,
      );

      expect(dueTodayTask.isDueToday, isTrue);
      expect(dueTodayTask.isOverdue, isFalse);
      expect(dueTodayTask.isUpcoming, isFalse);

      expect(overdueTask.isOverdue, isTrue);
      expect(overdueTask.isDueToday, isFalse);

      expect(upcomingTask.isUpcoming, isTrue);
      expect(upcomingTask.isOverdue, isFalse);

      expect(noDateTask.hasNoDueDate, isTrue);
      expect(noDateTask.isOverdue, isFalse);
      expect(noDateTask.isDueToday, isFalse);
    });
  });

  group('SchoolTask D-03 role permissions (canBeDeletedBy)', () {
    test('prevents student from deleting parent-created task while allowing parent or student-owned tasks', () {
      final now = DateTime.now();
      final parentTask = SchoolTask(
        id: 't_parent',
        familyId: 'jankiewicz_family',
        title: 'Zadanie od Taty',
        createdByRole: 'parent',
        createdByName: 'Tata',
        createdAt: now,
      );

      final studentTask = SchoolTask(
        id: 't_student',
        familyId: 'jankiewicz_family',
        title: 'Notatka własna Oskara',
        createdByRole: 'student',
        createdByName: 'Oskar',
        createdAt: now,
      );

      expect(parentTask.canBeDeletedBy(isStudent: true), isFalse);
      expect(parentTask.canBeDeletedBy(isStudent: false), isTrue);
      expect(studentTask.canBeDeletedBy(isStudent: true), isTrue);
      expect(studentTask.canBeDeletedBy(isStudent: false), isTrue);
    });
  });

  group('SchoolTask.sortUrgentForDashboard (D-08)', () {
    test('returns at most 5 active tasks sorted by Overdue -> DueToday -> Role/Priority', () {
      final now = DateTime.now();
      final today = DateTime(now.year, now.month, now.day);
      final yesterday = today.subtract(const Duration(days: 1));
      final tomorrow = today.add(const Duration(days: 1));

      final tasks = [
        SchoolTask(
          id: 'completed_1',
          familyId: 'jankiewicz_family',
          title: 'Zrobione zadanie',
          dueDate: yesterday,
          priority: TaskPriority.high,
          isCompleted: true,
          createdByRole: 'parent',
          createdByName: 'Tata',
          createdAt: now,
        ),
        SchoolTask(
          id: 'upcoming_low',
          familyId: 'jankiewicz_family',
          title: 'Jutro niskie',
          dueDate: tomorrow,
          priority: TaskPriority.low,
          assignedTo: TaskAssignee.student,
          createdByRole: 'student',
          createdByName: 'Oskar',
          createdAt: now,
        ),
        SchoolTask(
          id: 'today_parent_high',
          familyId: 'jankiewicz_family',
          title: 'Dzisiaj dla rodzica',
          dueDate: today,
          priority: TaskPriority.high,
          assignedTo: TaskAssignee.parent,
          createdByRole: 'parent',
          createdByName: 'Tata',
          createdAt: now,
        ),
        SchoolTask(
          id: 'today_student_med',
          familyId: 'jankiewicz_family',
          title: 'Dzisiaj dla Oskara normalne',
          dueDate: today,
          priority: TaskPriority.medium,
          assignedTo: TaskAssignee.student,
          createdByRole: 'student',
          createdByName: 'Oskar',
          createdAt: now,
        ),
        SchoolTask(
          id: 'today_student_high',
          familyId: 'jankiewicz_family',
          title: 'Dzisiaj dla Oskara pilne',
          dueDate: today,
          priority: TaskPriority.high,
          assignedTo: TaskAssignee.student,
          createdByRole: 'parent',
          createdByName: 'Tata',
          createdAt: now,
        ),
        SchoolTask(
          id: 'overdue_1',
          familyId: 'jankiewicz_family',
          title: 'Zaległe z wczoraj',
          dueDate: yesterday,
          priority: TaskPriority.medium,
          assignedTo: TaskAssignee.student,
          createdByRole: 'parent',
          createdByName: 'Tata',
          createdAt: now,
        ),
        SchoolTask(
          id: 'extra_6',
          familyId: 'jankiewicz_family',
          title: 'Szóste zadanie bez terminu',
          priority: TaskPriority.low,
          assignedTo: TaskAssignee.shared,
          createdByRole: 'student',
          createdByName: 'Oskar',
          createdAt: now,
        ),
      ];

      final sortedForStudent = SchoolTask.sortUrgentForDashboard(
        tasks,
        isStudent: true,
      );

      expect(sortedForStudent.length, equals(5));
      expect(sortedForStudent[0].id, equals('overdue_1'));
      expect(sortedForStudent[1].id, equals('today_student_high'));
      expect(sortedForStudent[2].id, equals('today_student_med'));
      expect(sortedForStudent[3].id, equals('today_parent_high'));
      expect(sortedForStudent[4].id, equals('upcoming_low'));
    });
  });
}
